// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdlxerisfnihpeqpnlwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkbHhlcmlzZm5paHBlcXBubHdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTc0NjcsImV4cCI6MjA2NTczMzQ2N30.nG5ubms5ahhwTAsCM0B_3A6WMGxsruPBMEpkX2Rx0hk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);